name: Deploy Admin to GitHub Pages
on:
  workflow_dispatch:
  push:
    paths:
      - 'admin/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build Admin
        working-directory: admin
        env:
          NEXT_PUBLIC_BASE_PATH: '/dkitchen-video'
        run: |
          npm install
          npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: admin/out
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4